/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package pl.kielce.tu.zwierzchowski.unitTests
{
	import flash.display.Sprite;
	
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_LevelsTest_obj:LevelsTest;
		private var flexUnitTests_ScoreManagerTest_obj:ScoreManagerTest;
		private var flexUnitTests_Level1Test_obj:Level1Test;
	}
}